name: HPack CI

on:
  schedule:
    - cron:  '0 3 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: |
        crystal spec -t -s
        crystal spec -Dpreview_mt
    - name: Run Ameba
      run: crystal run lib/ameba/bin/ameba.cr
    - name: Compile benchmarks
      run: |
        crystal build benchmark.cr -o /tmp/hpack-benchmark
        crystal build -Dpreview_mt benchmark.cr -o /tmp/hpack-benchmark-preview-mt
    - name: Build docs
      run: crystal docs
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
